version: '3'
services:
  watermill:
    image: golang:1.17
    command: /bin/true
    volumes:
      - .:/app
      - .mod-cache:/go/pkg/mod
    working_dir: /app

    environment:
      PUBSUB_EMULATOR_HOST: googlecloud:8085

  googlecloud:
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=googlecloud:8085 --verbosity=debug --log-http

